apiVersion: v1
kind: Service
metadata:
  name: fa3-clip-detector-svc
spec:
  type: NodePort
  selector:
    app: fa3-clip-detector
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
